/* ************************************************************************** */
/*                                                          LE - /            */
/*                                                              /             */
/*   ft_memcpy.c                                      .::    .:/ .      .::   */
/*                                                 +:+:+   +:    +:  +:+:+    */
/*   By: rgermain <marvin@le-101.fr>                +:+   +:    +:    +:+     */
/*                                                 #+#   #+    #+    #+#      */
/*   Created: 2018/10/01 19:19:53 by rgermain     #+#   ##    ##    #+#       */
/*   Updated: 2019/04/26 11:02:34 by rgermain    ###    #+. /#+    ###.fr     */
/*                                                         /                  */
/*                                                        /                   */
/* ************************************************************************** */

#include "libft.h"

char  *ft_errno[] =
{
    "Opération interdite",
    "Fichier ou répertoire inexistant",
    "Processus inexistant",
    "Appel système interrompu",
    "Erreur d’entrée-sortie"
    "Dispositif ou adresse inexistant"
    "Liste d’arguments trop longue",
    "Erreur de format d’exécution",
    "Mauvais descripteur de fichier",
    "Pas de processus fils",
    "Ressource temporairement indisponible (réessayez)",
    "Mémoire insuffisante",
    "Autorisation refusée",
    "Mauvaise adresse",
    "Dispositif de bloc requis",
    "Dispositif ou ressource occupé",
    "Fichier déjà existant",
    "Lien inapproprié",
    "Dispositif inexistant",
    "Pas un répertoire",
    "Est un répertoire",
    "Argument invalide",
    "Plus de descripteur de fichier disponible",
    "Trop de fichiers ouverts",
    "Opération de contrôle d’entrée-sortie invalide",
    "Fichier texte occupé",
    "Fichier trop grand",
    "Plus de place sur le dispositif",
    "Recherche invalide",
    "Système de fichiers en lecture seule",
    "Trop de liens symboliques",
    "Tube brisé",
    "Argument mathématique hors du domaine de définition de la fonction",
    "Résultat mathématique non représentable",
    "Un interblocage se produirait sur cette ressource",
    "Nom de fichier trop long",
    "Plus de verrou de fichier disponible",
    "Fonction non implémentée",
    "Dossier non vide",
    "Trop de liens symboliques trouvés",
    "L’opération bloquerait",
    "Pas de message du type voulu",
    "Identifiant supprimé",
    "Le numéro de canal est hors des limites",
    "Le niveau 2 n’est pas synchronisé",
    "Niveau 3 stoppé",
    "Niveau 3 réinitialisé",
    "Le numéro du lien est hors des limites",
    "Le pilote de protocole n’est pas attaché",
    "Pas de structure CSI disponible",
    "Niveau 2 stoppé",
    "Échange invalide",
    "Descripteur de requête invalide",
    "Échange complet",
    "Pas de anode",
    "Code de requête invalide",
    "Slot invalide",
    "Interblocage lors du verrouillage de fichier",
    "Mauvais format de fichier de police",
    "Le périphérique n’est pas un flux",
    "Pas de donnée disponible",
    "Délai maximal atteint",
    "Pas assez de ressources de type flux",
    "Machine hors réseau",
    "Paquet non installé",
    "L’objet est distant",
    "Lien coupé",
    "Erreur d’annonce",
    "Erreur Srmount",
    "Erreur de communication lors de l’envoi",
    "Erreur de protocole",
    "Transfert à sauts multiples essayé",
    "erreur spécifique RFS",
    "Pas un message de données",
    "Valeur trop grande pour être stockée dans ce type de donnée",
    "Nom non-unique dans le réseau",
    "Descripteur de fichier en mauvais état",
    "Adresse distante changée",
    "Accès impossible à une bibliothèque partagée nécessaire",
    "Accès à une bibliothèque partagée corrompue",
    "Section .lib de a.out corrompue",
    "Tentative de liaison entre trop de bibliothèques partagées",
    "Impossible d’exécuter directement une bibliothèque partagée",
    "Séquence de bytes illégale",
    "Appel système interrompu qui devrait être relancé",
    "Erreur d’enchaînement de flux",
    "Trop d’utilisateurs",
    "Opération socket pas sur un connecteur",
    "Adresse de destination obligatoire",
    "Message trop long",
    "Mauvais type de protocole pour ce connecteur",
    "Protocole pas disponible",
    "Protocole non géré",
    "Type de connecteur non géré",
    "Opération non gérée par cette fin de lien",
    "Famille de protocole non gérée",
    "Famille d’adresses non gérée par ce protocole",
    "Adresse déjà utilisée",
    "Impossible d’assigner l’adresse demandée",
    "Le réseau est désactivé",
    "Réseau inaccessible",
    "Connexion annulée par le réseau",
    "Connexion abandonnée",
    "Connexion réinitialisée",
    "Plus d’espace tampon disponible",
    "La socket est connectée",
    "La socket n’est pas connectée",
    "Impossible d’envoyer après l’arrêt du point final du transport",
    "Trop de descripteurs : impossible d’effectuer la liaison",
    "Délai maximal de connexion écoulé",
    "Connexion refusée",
    "Hôte éteint",
    "Pas de route vers l’hôte",
    "Connexion déjà en cours",
    "Opération en cours",
    "Descripteur de fichier NFS corrompu",
    "La structure a besoin d’être nettoyée",
    "N’est pas un fichier nommé du type XENIX",
    "Pas de sémaphore XENIX disponible",
    "Est un fichier nommé",
    "Erreur d’entrées-sorties distante",
    "Quota dépas",
};

char    *ft_strerror(int error)
{
    return ((char*)ft_errno[error]);
}